version: "3.8"

services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      ports:
        - "5432:5432"
    volumes: pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
