version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    network: -app-network

    backend:
      build:
        context: ./backend
        dockerfile: rust.dockerfile
      env_file: ./backend/.env
      environment:
        DATABASE_URL: ${POSTGRES_URL}
      ports:
        - "8000:8000"
      depends_on:
        - db
      network: -app-network
  db_migration:
    build:
      context: ./backend
      dockerfile: migrations.dockerfile
    env_file: ./backend/.env
    environment:
      DATABASE_URL: ${POSTGRES_URL}
    entrypoint: ["diesel", "migration", "run"]
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
