version: "4.3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file: ./backend/.env
    environment:
      DATABASE_URL: ${POSTGRES_URL}
    ports:
      - "8000:8000"
